name: CI pipline 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: task-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install

      - name: Run Linter
        run: npm run lint

      - name: Run Unit Tests
        run: npm run test

      - name: Build React App
        run: npm run build

      - name: Zip build folder
        run: zip -r build.zip dist

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: weather-app-build
          path: build.zip